FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN useradd -m appuser

WORKDIR /opt/pyend

COPY pyend/requirements.txt /opt/pyend/
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY ./pyend /opt/pyend/
RUN chown -R appuser:appuser /opt/pyend
USER appuser

WORKDIR /opt