name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Pytest
        run: |
          docker-compose up -d

          sleep 10

          pip install -r pyend/requirements.txt

          pytest

          docker-compose down
